// This file is automatically generated. Do not modify it manually.
// To change this configuration, please update your environment variables.
import { FirebaseOptions } from 'firebase/app';

// This is a placeholder for the Firebase configuration.
// In a real environment, this would be populated with your actual
// Firebase project configuration.
export const firebaseConfig: FirebaseOptions = {
  apiKey: process.env.NEXT_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_APP_ID,
};
